"""empty message

Revision ID: 0498a9db3748
Revises: b2b1f75a2253
Create Date: 2023-12-18 11:28:24.785826

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0498a9db3748'
down_revision = 'b2b1f75a2253'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classroom', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'dormitory', ['classroom_id'], ['id'])
        batch_op.create_foreign_key(None, 'student', ['student_id'], ['id'])

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'classroom', ['classroom_id'], ['id'])
        batch_op.create_foreign_key(None, 'student', ['student_id'], ['id'])

    with op.batch_alter_table('floor', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'dormitory', ['dormitory_id'], ['id'])

    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'dormitory', ['dormitory_id'], ['id'])

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'dormitory', ['dormitory_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('join_time', sa.DateTime(), nullable=True))
        batch_op.alter_column('password',
                              existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=100),
                              type_=sa.String(length=200),
                              existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
                              existing_type=sa.String(length=200),
                              type_=mysql.VARCHAR(collation='utf8_unicode_ci', length=100),
                              existing_nullable=False)
        batch_op.drop_column('join_time')

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('floor', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('classroom', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
