"""empty message

Revision ID: b2b1f75a2253
Revises: 
Create Date: 2023-12-18 02:02:49.403296

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b2b1f75a2253'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classroom', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'dormitory', ['classroom_id'], ['id'])

    with op.batch_alter_table('email_captcha', schema=None) as batch_op:
        batch_op.alter_column('email',
                              existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=120),
                              type_=sa.String(length=100),
                              existing_nullable=False)

    with op.batch_alter_table('floor', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'dormitory', ['dormitory_id'], ['id'])

    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'dormitory', ['dormitory_id'], ['id'])

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'dormitory', ['dormitory_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('floor', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('email_captcha', schema=None) as batch_op:
        batch_op.alter_column('email',
                              existing_type=sa.String(length=100),
                              type_=mysql.VARCHAR(collation='utf8_unicode_ci', length=120),
                              existing_nullable=False)

    with op.batch_alter_table('classroom', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
